version: '3'

services:
  app:
    image: 'my-riot-image'
    build:
      context: .
    container_name: app
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://riotdb:5432/riot
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12344321

  db:
    image: postgres:14.1-alpine
    container_name: riotdb
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12344321
      - POSTGRES_DB=riot
    volumes:
      - db_data:/var/lib/postgresql/data



volumes:
  db_data:
